-- Spring security tables
CREATE TABLE users(username varchar(100) NOT NULL,
				   first_name varchar(250) NOT NULL,
				   middle_name varchar(100),
				   surname varchar(250),
				   password varchar(100) NOT NULL, 
				   enabled boolean not null default false);
				   
CREATE TABLE authorities (username varchar(50) not null,
      					  authority varchar(50) not null,
      					  constraint fk_authorities_users foreign key(username) references users(username));
CREATE UNIQUE INDEX ix_auth_username on authorities (username,authority);

-- Application Tables
CREATE TABLE customer(customer_id varchar(100) NOT NULL, name varchar(250) NOT NULL, email varchar(250), PRIMARY KEY(customer_id));
CREATE TABLE barcode(barcode_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY, 
					 barcode_api_key varchar(250) NOT NULL, customer_id varchar(100), barcode_format varchar(20), 
					 constraint fk_customer foreign key(customer_id) references customer(customer_id));
CREATE UNIQUE INDEX ix_barcode_api_key on barcode (barcode_api_key);

CREATE TABLE barcode_policy(id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY, 
					 domain varchar(4) NOT NULL, barcode_id BIGINT, width INTEGER, height INTEGER, active boolean NOT NULL default false,
					 constraint fk_barcode foreign key(barcode_id) references barcode(barcode_id));


--- Users
INSERT INTO users values ('nmishra', 'Nitin', null, 'Mishra', '$2a$10$7gYm2/MbFNnzRQAOpUDAi.G52cVDlDnrXdSFe3jgyiJhRNmipgn4a', true);
INSERT INTO authorities values ('nmishra', 'ROLE_ADMIN');

--- Customers
INSERT INTO customer values ('tescos123', 'Tesco', 'tescos@tesco.co.uk');
INSERT INTO customer values ('argos123', 'Argos', 'argoss@argos.co.uk');
INSERT INTO customer values ('sainsburys123', 'Sainsburys', 'sainsburyss@sainsburys.co.uk');

--- Barcodes
INSERT INTO barcode (barcode_api_key, customer_id, barcode_format) values ('tescos123code128apikey', 'tescos123', 'code128');
INSERT INTO barcode (barcode_api_key, customer_id, barcode_format) values ('tescos123code39apikey', 'tescos123', 'code39');
INSERT INTO barcode (barcode_api_key, customer_id, barcode_format) values ('tescos123qrcodeapikey', 'tescos123', 'qrcode');

